name: Publish Alpha Version

on:
  commit_comment: [Publish-Alpha]
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Build packages
      run: dotnet pack --configuration Release
    - name: Publish packages
      run: dotnet nuget push ./*/nupkg/*.nupkg --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_API_KEY}} --version-suffix alpha
