name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish-alpha:
    if: "github.event.release.prerelease"
    name: Publish Alpha
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build packages
      run: dotnet pack --configuration Release /p:Version="${{github.event.release.tag_name}}"
    - name: Publish packages
      run: dotnet nuget push ./*/nupkg/*.nupkg --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_API_KEY}} --version-suffix alpha
  
  publish:
    if: "!github.event.release.prerelease"
    name: Publish Alpha
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build packages
      run: dotnet pack --configuration Release /p:Version="${{github.event.release.tag_name}}"
    - name: Publish packages
      run: dotnet nuget push ./*/nupkg/*.nupkg --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_API_KEY}}
